### ISSUE TITLE
Postman collection not able to run using newman command line

### ISSUE THREAD

**Issue by zac11** [BigstickCarpet/postman-bdd#14]
I am trying to run a collection of Postman tests, which are using Postman-BDD Library for simple tests. I started using the newman command line runner to run the tests. However, I am getting a Reference Error for the `describe` used in the tests.

Here is my tests

eval(globals.postmanBDD);

describe("Success Failure Check",()=>{
      it('response should be ok', () => {
    response.ok.should.be.true;
});

  it('HTTP code returned should be 200', () => {
    response.should.have.status(200);
});

  it('response should not be error', () => {
    response.error.should.be.false;
});
});

The tests pass, but the Newman command line throughs an error - which I am not able to understand, since I installed newman globally. I have attached the image for the failure -

[Error in Newman](http://imgur.com/yONdDys)

I have gone through the newman npm page, and I see that it integrates well with the library. So I am not able to get why I'm getting this error.

**Comment by zac11** [comment]
@BigstickCarpet

**Comment by BigstickCarpet** [comment]
When you create global/environment variables in the Postman app, they don't automatically exist in the Newman CLI.  You either need to re-create those variables in Newman, or you need to import them using the `--globals` or `--environment` [command line arguments](https://github.com/postmanlabs/newman#command-line-options)

I suggest that you always [install Postman BDD](https://github.com/BigstickCarpet/postman-bdd#installation) as the first request in your collection.  That way the collection works anywhere you run it, without relying on the existence of global/environment variables.

**Comment by zac11** [comment]
Thanks @BigstickCarpet . I implemented the second suggestion that you gave. Thanks a lot. Can you give an example of how to do the first option , using the `--globals` flag.

**Comment by BigstickCarpet** [comment]
See the [Postman documentation](https://www.getpostman.com/docs/postman/environments_and_globals/manage_globals) and the [Newman documentation](https://github.com/postmanlabs/newman#command-line-options) for details about managing globals.
