### ISSUE TITLE
BDD Library gives error on checking Content-Length header

### ISSUE THREAD

**Issue by zac11** [BigstickCarpet/postman-bdd#15]
I have a RESTful API, that returns a `Content-Length` as one of it's response headers. I want to assert that the length of this header is below 2000.

In my Postman app, I can see that the `Content-Length` header returns a value of 539. 

If I use this assertion, 
`
it('response should have content length below 2000',()=>{
          response.should.have.header('Content-Length').and.should.be.an('object');`

it passes, since the returned header is of type `object`. Now if I want to assert that the value of the `Content-Length` is below 2000, I'm using this assertion

`response.should.have.header('Content-Length').and.should.be.below(2000);`

but this fails stating
`expected [object Object] to be a number or a date`

As per the this [post](https://stackoverflow.com/questions/2773396/whats-the-content-length-field-in-http-header) , `Content-Length` is returned as an decimal number of octet, so I changed the value to be 

`response.should.have.header('Content-Length').and.should.be.below(3720);` [octet of 2000]

but this also fails. 

How can I assert that the `Content-Length` is below 2000?

**Comment by BigstickCarpet** [comment]
A few things to point out here:

**1.** The `.header()` assertion doesn't change the assertion target.  So your `.and.should.be.below(2000)` assertion is still asserting on the `response` object, not the `Content-Length` header.  Here's a demonstration of that:

```javascript
response.should.have.header('Content-Length').and.equal(response);
```

**2.** [Chai-HTTP](https://github.com/chaijs/chai-http) doesn't have an assertion for comparing a header to a range of values, only to [a specific value](https://github.com/chaijs/chai-http#header-key-value).  This is handy if you know the _exact_ content-length that you expect.

```javascript
response.should.have.header('Content-Length', '2000');
```

**3.** All HTTP headers are strings.  So you can't compare the Content-Length header to a numeric range unless you first convert it to a number.  Once you've done that, you can use [any Chai.js assertion](http://chaijs.com/api/bdd/) you want.  In your case, I believe you'd want something like this:

```javascript
let contentLength = parseInt(response.headers["content-length"]);
contentLength.should.be.below(2000);
```

**Comment by zac11** [comment]
I 'm gonna close this one. Thanks @BigstickCarpet for the help.
