### ISSUE TITLE
Integration broken and Test cases not updated back due to Test link as assertion number "1. SP-3751:Get response 200"

### ISSUE THREAD

**Issue by shriharshdesai** [BigstickCarpet/postman-bdd#16]
please help me with command to exclude the numbers from Assertion result

1. SP-3751:Get response 200
2. SP-3752:Get response 300

**Comment by shriharshdesai** [comment]
Earlier in BDD ver 1.0.5 , there were no numbering for assertions.

**Comment by BigstickCarpet** [comment]
Hi @shriharshdesai.  The numbers at the beginning of the test names were added in [this commit](https://github.com/BigstickCarpet/postman-bdd/commit/5ef9606b756e44d5ec0ae899c257838bef5a44be), which was first included in [Postman BDD v4.0](https://github.com/BigstickCarpet/postman-bdd/blob/master/CHANGELOG.md#v400-2017-03-06).

If you wish to continue using Postman BDD v3.0, then you can change the download link in your collection to point to `http://bigstickcarpet.com/postman-bdd/dist/v3/postman-bdd.min.js`.

**Comment by shriharshdesai** [comment]
Thanks @BigstickCarpet
