### ISSUE TITLE
Asserting header contents

### ISSUE THREAD

**Issue by zac11** [BigstickCarpet/postman-bdd#18]
I have an API, which pulls a token out and we have to use that token in subsequent requests. In the CSRF token, I am getting lot of headers and I want to assert if their values are above certain value.

I am particularly concerned about the `Keep-Alive` header. The response header that I am recieving is

`Keep-Alive →timeout=15, max=98`

where the max value keep changing to 98-100. I want to assert that we have this value above , say 95+. How would I achieve this using the library.

**Comment by BigstickCarpet** [comment]
You can get the `Keep-Alive` header via the `response.headers['keep-alive']` property, or the `response.getHeader("Keep-Alive")` method (the former is all lowercase, the latter is case-insensitive).  Either way, the header value is just a string, and you can do whatever string parsing and validation you want. 

For example:
```javascript
// Get the Keep-Alive header
let keepAlive = response.getHeader("Keep-Alive");

// Make sure it contains "max=##"
let match = /max=(\d+)/.exec(keepAlive);
expect(match).to.be.an("array").and.not.empty;

// Make sure the max is between 98 and 100
let max = parseInt(match[1]);
expect(max).to.be.at.least(98).and.at.most(100);
```

**Comment by zac11** [comment]
Cool. This works. Thanks again @BigstickCarpet :)
