### ISSUE TITLE
try to get postman-bdd got "Unexpected '/' " result

### ISSUE THREAD

**Issue by yeugeneu** [BigstickCarpet/postman-bdd#22]
When I try to GET the url with 
`postman.setGlobalVariable('postmanBDD', responseBody);`

Got response body as
`Unexpected '/'`

**Comment by BigstickCarpet** [comment]
Check the response code to make sure you're getting back a  200 response, not a 404 or some other error response.  If you _are_ getting back an error, then double-check to make sure you've entered the PostmanBDD URL correctly

**Comment by yeugeneu** [comment]
I do get 200 response code however the response body is still 
`Unexpected '/'`

<img width="887" alt="screen shot 2018-02-19 at 9 40 09 am" src="https://user-images.githubusercontent.com/1661795/36390826-2bd877ea-1559-11e8-811b-5df536685fb4.png">

**Comment by BigstickCarpet** [comment]
You have "JSON" selected as the response format, which is incorrect.  Set it to "Auto" instead and you'll see the actual response body

**Comment by yeugeneu** [comment]
@BigstickCarpet no wonder!! thanks for point it out!
