### ISSUE TITLE
False negatives

### ISSUE THREAD

**Issue by otoniel-isidoro** [BigstickCarpet/postman-bdd#5]
Given a test example:

```
describe('Products API', function(){
    it('should return a valid JSON response', function(){
        expect(response).to.be.json;
        expect(response.body).to.not.be.empty;
        expect(response.body).to.have.schema(schema);
    });
    
    it('should return 200 as status code', function(){
        expect(response).to.have.status(200);
    });
   
    it('should not take more than ' + globals.lowResponseTime + ' miliseconds', function(){
        expect(responseTime).to.be.at.most(globals.lowResponseTime);
    });
});
```

After I runned  the test  the following errors were shown:

``` 
* Products API should not take more than 200 miliseconds to load
* expected 519 to be at most 200
```
 
The problem is that the second failure is just a better explanation for the first one and it give an impression of false negative. 
I understood  that the first is about the scenario described on the it statement and the second is about the assertion made, but I think a better approach can be join the 2 messages because it is about the same failure. 
Given another example with multiples assertions inside the same 'it' statement I think it should be join on the same failure too because all the assertions inside the same 'it' is about the same test. 
Another problem is that on the final test report the number of failed test-scripts isn't correct and is always 0. 

Example:

```

┌─────────────────────────┬──────────┬──────────┐
│                         │ executed │   failed │
├─────────────────────────┼──────────┼──────────┤
│              iterations │        1 │        0 │
├─────────────────────────┼──────────┼──────────┤
│                requests │       61 │        0 │
├─────────────────────────┼──────────┼──────────┤
│            test-scripts │       60 │        0 │
├─────────────────────────┼──────────┼──────────┤
│      prerequest-scripts │        3 │        0 │
├─────────────────────────┼──────────┼──────────┤
│              assertions │      223 │       70 │
├─────────────────────────┴──────────┴──────────┤
│ total run duration: 2m 0s                     │
├───────────────────────────────────────────────┤
│ total data received: 130.17KB (approx)        │
├───────────────────────────────────────────────┤
│ average response time: 1894ms                 │
└───────────────────────────────────────────────┘



```

**Comment by BigstickCarpet** [comment]
Good point about the double-negative issue.  I'll change the behavior to just append the assertion failure message to the test name.

As for the number of failed test scripts in the Newman CLI... I believe that's the intended behavior, but I'm not 100% sure because I don't work on that project.  You can [open an issue on that project](https://github.com/postmanlabs/newman/issues) if you want

**Comment by BigstickCarpet** [comment]
I've fixed the double-negative issue.
