### ISSUE TITLE
Create typescript definition for postman-bdd

### ISSUE THREAD

**Issue by urosjarc** [BigstickCarpet/postman-bdd#6]
I'm creating e2e postman tests localy in code, example for postman call: 
```js
"use strict";

const postman = require('../postman');

exports.name = 'getAdvice';
exports.description = 'Advice list';

exports.request = {
  url: " {{url}}/v1/collections/HW2016_RUNNING__IDE",
  method: "GET",
  header: [
    {
      key: 'x-api-key',
      value: '{{x-api-key}}'
    }
  ]
};

exports.event = [
  postman.events.test(() => {
    describe('Get customer info', () => {
      it('should return a 200 response', () => {
        response.should.have.status(200);
      });
    });
  })
];
```

And it would speed up my process of writing tests if postman-bdd would have somekind of typescript definition file which would make IDE hinting more acurate for faster development.

**Comment by urosjarc** [comment]
npm install --save-dev @types/chai
npm install --save-dev @types/chai-http

**Comment by BigstickCarpet** [comment]
Good idea!  I've never used TypeScript, so I'm not familiar with how to create TypeScript definition files, but if someone else wants submit a PR, I'll gladly merge it

**Comment by urosjarc** [comment]
I'm doing it right now, tomorow i will try to make PR. Maybe it would be nice to push  it on https://github.com/DefinitelyTyped/DefinitelyTyped

**Comment by BigstickCarpet** [comment]
Just to help with the definition file... Here are the top-level global variables that Postman BDD exposes, and their properties/methods:

```
describe([string], function)
it([string], function)
before([string], function)
after([string], function)
beforeEach([string], function)
afterEach([string], function)

assert(boolean, [string])
expect([any])

postmanBDD
  .logLevel - string

request
  .method - string
  .url - string
  .headers - object
  .data - object

response
  .status - number
  .statusType - number
  .info - boolean
  .ok - boolean
  .redirect - boolean
  .clientError - boolean
  .serverError - boolean
  .error - boolean
  .accepted - boolean
  .noContent - boolean
  .badRequest - boolean
  .unauthorized - boolean
  .notAcceptable - boolean
  .notFound - boolean
  .forbidden - boolean
  .time - number
  .headers - object
  .type - string
  .charset - string
  .cookies - object
  .text - string
  .body - object
  .getHeader(string)
  .getCookie(string)

chai
  .use(function)
  .assert(boolean, [string])
  .expect([any])
  .should

object
  .should
  .to
  .be
  .been
  .is
  .that
  .which
  .and
  .has
  .have
  .with
  .at
  .of
  .same
  .a
  .an
  .equal
  .deep
  .... (all the rest of the Chai and Chai-Http assertions)
```

**Comment by urosjarc** [comment]
Thanx man! Much appreciated!

**Comment by BigstickCarpet** [comment]
btw, @urosjarc, I'm very interested in your API testing approach.  You appear to be writing all of your tests in Node.js, and dynamically generating a Postman Collection, which I presume you then run via [Newman](https://www.npmjs.com/package/newman).  Is that correct?  Are you using the [Postman Collection SDK](http://www.postmanlabs.com/postman-collection/index.html) to generate the collection file?  Or are you generating it using your own custom code?

Is your project open-source?  I'd love to see your code that builds the collection file and runs it.

**Comment by urosjarc** [comment]
Well its nothing special, i'm developing e2e testing arhitecture for ???? company. But I hate that all the tests was on remote postman server with no version control system, IDE support, hintings etc... (This is how I found your lib) GOOGLE: Include external npm packages to postman tests xD. Anyhow, I was thinking how can I create my local e2e tests and how to create good syncing with local and remote collection. So I figure it out that the best way was to create postman collection from node modules.

```
e2e
├── Advices                 <- Postman folder
│   ├── getAdvice.js     <- Folder request + tests
│   └── index.js            <- Folders info require('./getAdvice')
├── index.js                 <- Collections info require('./Advice')   
├── postman.js            <- Helper methods
└── postman.d.ts         <- Postman hints 
```

If you require node module, the result is json object... (if create good structure the structure its self is postman collection). For tests I stringify function body (search Stackowerflow).

For build tasks I use official postman API:
```
gulp.task('postman:diff', 'Create diff report for remote and local e2e tasks.', ['postman:backup'], (cb) => {
  jsonDiff([path.join(__dirname, 'docs/remote.postman.json'), path.join(__dirname, 'build/e2e.postman.json')]);
  cb();
});

gulp.task('postman:backup', 'Back up local and remote collection.', ['postman:pull'], () => {
  const backupPath = path.join(__dirname, 'build', 'e2e.postman.json');
  gutil.log('>', 'E2E backup exported to:', backupPath);
  fs.writeFileSync(backupPath, JSON.stringify(e2e, null, '\t'));
});

gulp.task('postman:push', 'Push local postman e2e collection to remote postman collection.', ['test:e2e'], (cb) => {

  const options = {
    "method": "PUT",
    "hostname": postmanConfig.api.url,
    port: null,
    "path": `/collections/${postmanConfig.collections_uid}`,
    "headers": {
      "x-api-key": postmanConfig.api.key
    }
  };

  const req = http.request(options, (res) => {
    const chunks = [];

    res.on("data", (chunk) => {
      chunks.push(chunk);
    });

    res.on("end", () => {
      const body = Buffer.concat(chunks);
      console.log(JSON.stringify(JSON.parse(body.toString()), null, '  '));
      cb();
    });
  });

  req.write(JSON.stringify({
    collection: e2e
  }));

  req.end();
});

gulp.task('postman:list', 'List remote postman collections.', (cb) => {

  const options = {
    "method": "GET",
    "hostname": postmanConfig.api.url,
    port: null,
    "path": '/collections',
    "headers": {
      "x-api-key": postmanConfig.api.key
    }
  };

  const req = http.request(options, (res) => {
    const chunks = [];

    res.on("data", (chunk) => {
      chunks.push(chunk);
    });

    res.on("end", () => {
      const body = Buffer.concat(chunks);
      JSON.parse(body.toString()).collections.forEach((ele) => {
        console.log(` > ${ele.name}`);
        console.log(`    - Owner: ${ele.owner}`);
        console.log(`    - UID: ${ele.uid}`);
        console.log(`    - ID: ${ele.id}`);
      });
      cb();
    });
  });

  req.end();
});

gulp.task('postman:pull', 'Pull remote postman collection to docs folder.', (cb) => {

  const options = {
    "method": "GET",
    "hostname": postmanConfig.api.url,
    port: null,
    "path": `/collections/${postmanConfig.collections_uid}`,
    "headers": {
      "x-api-key": postmanConfig.api.key
    }
  };

  const req = http.request(options, (res) => {
    const chunks = [];

    res.on("data", (chunk) => {
      chunks.push(chunk);
    });

    res.on("end", () => {
      const body = Buffer.concat(chunks);
      const filePath = path.join(__dirname, './docs/remote.postman.json');
      gutil.log('>', 'POSTMAN backup exported to:', filePath);
      fs.writeFileSync(filePath,
        JSON.stringify(JSON.parse(body.toString()).collection, null, '\t')
      );
      cb();
    });
  });

  req.end();
});
```

***You know what it would be cool! To create 'gulp-postman' lib which would integrate postman api like I did... Are you interested in colaboration?***

**Comment by urosjarc** [comment]
Wait what? Are you working in postmanlabs? What? And I'm inviting you for colaboration xD

**Comment by BigstickCarpet** [comment]
Haha... yes, I work at Postman.  I really like your approach, and I'm thinking about how it could be made more generic to work for more people.  I'd make it a standalone npm package (no Gulp dependency) and then create a separate npm package for the Gulp plugin (the plugin would just wrap the standalone npm package)

**Comment by urosjarc** [comment]
I would really like to see for example mocha like postman lib which would detect e2e structure automaticly and parse e2e testing structure to newman:

```
describe_folder('POSTMAN_FOLDER', 'description', () => {
        describe_route('GET','{{url}}/some/path', () => {
                it('returns 200', () => {...})
                it('returns 200', () => {...})
        });
});
```

**Comment by urosjarc** [comment]
It would be nice to move this conversation to private chanels... gitter maybe?

**Comment by urosjarc** [comment]
I will create pull requests in [DefinitelyTyped](https://github.com/DefinitelyTyped/DefinitelyTyped).
One for postman-test, and one for postman-dbb.d.ts in your repository.

**Comment by urosjarc** [comment]
@BigstickCarpet : Is it possible to put [postman-sandbox types definitions](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/15691/commits/88f1a55a5ae47ea6637c03e45b3a9734d14b3580) here in to your repository?

**Comment by BigstickCarpet** [comment]
Yep!  Go ahead.  Since Postman BDD only works inside the Postman Sandbox, it makes sense to include both type definitions
