### ISSUE TITLE
Not much of an issue

### ISSUE THREAD

**Issue by gauravshetti** [BigstickCarpet/postman-bdd#8]
Hey I really love the ongoing project. Is there a way we can add release notes so that we know what really changed from a birds eye view.

**Comment by BigstickCarpet** [comment]
Yep.  Good point.  I'll add a changelog and start adding info about significant changes 👍

**Comment by gauravshetti** [comment]
👍 awesomeness

**Comment by urosjarc** [comment]
@BigstickCarpet : I use this one to generate changelog: [github-changelog-generator](https://github.com/skywinder/github-changelog-generator)

And here is my gulp task: [gitbook-plugin-build/gulpfile.js#L154](https://github.com/urosjarc/gitbook-plugin-build/blob/master/gulpfile.js#L154)

**Comment by BigstickCarpet** [comment]
@gauravshetti - Sorry for taking so long on this.  I just added a [changelog](https://github.com/BigstickCarpet/postman-bdd/blob/master/CHANGELOG.md) and back-filled it to v3.0

**Comment by gauravshetti** [comment]
👍
