### ISSUE TITLE
Array assertion expects the returned JSON to be an Object.

### ISSUE THREAD

**Issue by zac11** [BigstickCarpet/postman-bdd#9]
I am using the Postman BDD library for asserting my JSON response from an API. The API response returned is an array like this -

[
               {
                       "last_page": 1,
                       "locality": [
                                {
                                    "name": "Delhi",
                                      "id": 464
                                },
                               {
                                   "name": "Mumbai",
                                     "id": 102242
                               },
                              {
                                  "name": "Kolkata",
                                   "id": 465
                             },
                            {
                                  "name": "Chennai",
                                  "id": 2349
                             },
                            {
                                  "name": "Bangaluru",
                                  "id": 41444
                            },
                           {
                                  "name": "Hyderabad",
                                   "id": 3843
                           }
                                ]
             }
]

My assertion for this is to check if the returned response is an array -

`describe("checking the response and keys",()=>{
   it("response is a JSON object",()=>{
      response.should.be.an("Array"); 
   });
`

However, this is returning in an error, saying - **expected {Object(status,statusType,...)} to be an array.**

**Comment by BigstickCarpet** [comment]
You're doing an assertion directly on the `response` object (which is why you see `Object(status,statusType,...)` in the error message).  Instead, you should be asserting on the `response.body` property, which will contain your parsed JSON response.

i.e. change your code to this:

```javascript
describe("checking the response and keys", () => {
    it("response is a JSON object", () => {
        response.body.should.be.an("Array");
    });
});
```

**Comment by BigstickCarpet** [comment]
Also, for future reference... you can use [`console.log()`](http://blog.getpostman.com/2016/08/26/the-postman-console/) statements to help you debug your test scripts in Postman.  For example, in this case, it might have been helpful if you had logged the `response` object to see exactly what it looked like.

```javascript
console.log(response);
```

Then, you could open the [Postman Console](http://blog.getpostman.com/2016/08/26/the-postman-console/) to view the logged object.

**Comment by zac11** [comment]
Thanks for the response. I see the mistake. The assertion should have been on the response body and not on the whole response. Closing this issue.
